### ISSUE TITLE
List index out of range

### ISSUE THREAD

**Issue by jcuenod** [JonathanReeve/text-matcher#13]
Does this mean there are no matches?

```
Traceback (most recent call last):
  File "/home/jcuenod/.local/bin/text-matcher", line 11, in <module>
    load_entry_point('text-matcher==0.1.5', 'console_scripts', 'text-matcher')()
  File "/home/jcuenod/.local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/jcuenod/.local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/jcuenod/.local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jcuenod/.local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/jcuenod/.local/lib/python3.7/site-packages/text_matcher/text_matcher.py", line 134, in cli
    prevTextObjs[filename] = Text(texts[filename], filename)
  File "/home/jcuenod/.local/lib/python3.7/site-packages/text_matcher/matcher.py", line 27, in __init__
    self.tokens = self.getTokens(removeStopwords)
  File "/home/jcuenod/.local/lib/python3.7/site-packages/text_matcher/matcher.py", line 39, in getTokens
    self.length = spans[-1][-1]
IndexError: list index out of range
```

**Comment by JonathanReeve** [comment]
Hm. It seems to think that there are one or fewer words in that document. You're not giving it a blank document?

**Comment by JonathanReeve** [comment]
I just wrapped that code in a try/except that should fix that, I hope. Could you pull the latest version (from here on GitHub), and try again, and let me know if it works?

**Comment by jcuenod** [comment]
Sorry for the lack of response previously.
No I was not giving it a blank document. I see that this change was partially in response to the latest issue, I've subscribed to it and I'll follow its development. Tbh, I'm using the package from `pip` so I haven't even cloned the repo yet...

**Comment by JonathanReeve** [comment]
Ok, I'll close this issue in favor of #14, then. If you could try again using the latest version from GitHub, and let me know if that works, that'd be great.
